Repository prgrms-web-devcourse-final-project/WEB5_7_3star_BE, pull requests merged in 2025-07, with the labels that each got.

#14 feat: 쿠폰 발급기능 구현
  src/main/java/com/threestar/trainus/domain/coupon/controller/CouponController.java
  src/main/java/com/threestar/trainus/domain/coupon/dto/CreateUserCouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/dto/Temp.java
  src/main/java/com/threestar/trainus/domain/coupon/entity/UserCoupon.java
  src/main/java/com/threestar/trainus/domain/coupon/mapper/UserCouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/CouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/service/CouponService.java
  src/main/java/com/threestar/trainus/global/entity/BaseDateEntity.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
Labels: feat

#21 feat: swagger 적용 및 작동 테스트
  build.gradle
  src/main/java/com/threestar/trainus/domain/lesson/student/controller/StudentLessonController.java
  src/main/java/com/threestar/trainus/global/config/CorsConfig.java
  src/main/java/com/threestar/trainus/global/config/SecurityConfig.java
  src/main/java/com/threestar/trainus/global/config/SwaggerConfig.java
Labels: feat

#22 feat: 이메일 인증 구현
  build.gradle
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/dto/EmailSendRequestDto.java
  src/main/java/com/threestar/trainus/domain/user/dto/EmailSendResponseDto.java
  src/main/java/com/threestar/trainus/domain/user/dto/EmailVerificationDto.java
  src/main/java/com/threestar/trainus/domain/user/service/EmailVerificationService.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
  src/main/resources/templates/verification.html
Labels: feat

#31 feat: 프로필/메타데이터/퍼사드 패턴 구현
  src/main/java/com/threestar/trainus/domain/metadata/dto/ProfileMetadataResponseDto.java
  src/main/java/com/threestar/trainus/domain/metadata/entity/ProfileMetadata.java
  src/main/java/com/threestar/trainus/domain/metadata/mapper/ProfileMetadataMapper.java
  src/main/java/com/threestar/trainus/domain/metadata/repository/ProfileMetadataRepository.java
  src/main/java/com/threestar/trainus/domain/metadata/repositroy/ProfileMetadataRepository.java
  src/main/java/com/threestar/trainus/domain/metadata/service/ProfileMetadataService.java
  src/main/java/com/threestar/trainus/domain/profile/controller/ProfileController.java
  src/main/java/com/threestar/trainus/domain/profile/dto/ProfileDetailResponseDto.java
  src/main/java/com/threestar/trainus/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/threestar/trainus/domain/profile/dto/ProfileUpdateRequestDto.java
  src/main/java/com/threestar/trainus/domain/profile/dto/TempDto.java
  src/main/java/com/threestar/trainus/domain/profile/entity/Profile.java
  src/main/java/com/threestar/trainus/domain/profile/mapper/ProfileDetailMapper.java
  src/main/java/com/threestar/trainus/domain/profile/mapper/ProfileMapper.java
  src/main/java/com/threestar/trainus/domain/profile/repository/ProfileRepository.java
  src/main/java/com/threestar/trainus/domain/profile/service/ProfileFacadeService.java
  src/main/java/com/threestar/trainus/domain/profile/service/ProfileService.java
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
  src/main/java/com/threestar/trainus/global/config/SecurityConfig.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
Labels: feat

#35 fix: 세션 인증 정보 SecurityContext에 주입
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
  src/main/java/com/threestar/trainus/global/config/security/SecurityConfig.java
  src/main/java/com/threestar/trainus/global/config/security/SessionAuthenticationFilter.java
Labels: bug

#38 fix: 프로필 메타데이터 연관관계 빼먹음
  src/main/java/com/threestar/trainus/domain/user/entity/User.java
Labels: bug

#48 feat: 내 레슨 신청 현황, 레슨 요약 조회 구현
  src/main/java/com/threestar/trainus/domain/lesson/admin/repository/LessonApplicationRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/student/controller/StudentLessonController.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSimpleResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSummaryResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/MyLessonApplicationListResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/MyLessonApplicationResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/service/StudentLessonService.java
Labels: feat

#40 feat: 쿠폰 발급 동시성 제어 구현
  src/main/java/com/threestar/trainus/domain/coupon/controller/CouponController.java
  src/main/java/com/threestar/trainus/domain/coupon/entity/Coupon.java
  src/main/java/com/threestar/trainus/domain/coupon/entity/UserCoupon.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/CouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/service/CouponService.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
  src/test/java/com/threestar/trainus/coupon/CouponServiceTests.java
Labels: feat

#49 Refactor: 조회 쿼리개선
  src/main/java/com/threestar/trainus/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/CouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/service/CouponService.java
Labels: refactor

#57 feat: 레슨 검색 API 구현
  src/main/java/com/threestar/trainus/domain/lesson/admin/repository/LessonParticipantRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/admin/repository/LessonRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/student/controller/StudentLessonController.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSearchListResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSearchResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/mapper/LessonSearchMapper.java
  src/main/java/com/threestar/trainus/domain/lesson/student/service/StudentLessonService.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
Labels: feat

#52 feat: s3설정, 업로더구현
  build.gradle
  src/main/java/com/threestar/trainus/global/config/S3Config.java
  src/main/java/com/threestar/trainus/global/controller/S3TestController.java
  src/main/java/com/threestar/trainus/global/utils/S3Uploader.java
Labels: feat

#50 feat: 랭킹 조회 기능 구현
  src/main/java/com/threestar/trainus/domain/metadata/mapper/ProfileMetadataMapper.java
  src/main/java/com/threestar/trainus/domain/profile/controller/ProfileController.java
  src/main/java/com/threestar/trainus/domain/profile/dto/ProfileUpdateRequestDto.java
  src/main/java/com/threestar/trainus/domain/profile/mapper/ProfileDetailMapper.java
  src/main/java/com/threestar/trainus/domain/profile/mapper/ProfileMapper.java
  src/main/java/com/threestar/trainus/domain/ranking/controller/RankingController.java
  src/main/java/com/threestar/trainus/domain/ranking/dto/RankingData.java
  src/main/java/com/threestar/trainus/domain/ranking/dto/RankingResponseDto.java
  src/main/java/com/threestar/trainus/domain/ranking/repository/RankingRepository.java
  src/main/java/com/threestar/trainus/domain/ranking/service/RankingService.java
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/dto/EmailSendRequestDto.java
  src/main/java/com/threestar/trainus/domain/user/dto/SignupRequestDto.java
  src/main/java/com/threestar/trainus/domain/user/entity/User.java
  src/main/java/com/threestar/trainus/domain/user/mapper/UserMapper.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
  src/main/java/com/threestar/trainus/global/config/MockDataInitializer.java
  src/main/java/com/threestar/trainus/global/config/SchedulerConfig.java
  src/main/java/com/threestar/trainus/global/config/security/SecurityConfig.java
Labels: feat

#68 feat: 공통예외 메서드 getUserById
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
Labels: feat

#72 refactor: 이메일 인증 리팩토링
  src/main/java/com/threestar/trainus/domain/metadata/service/ProfileMetadataService.java
  src/main/java/com/threestar/trainus/domain/profile/service/ProfileService.java
  src/main/java/com/threestar/trainus/domain/user/service/EmailVerificationService.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
Labels: refactor

#71 feat : 쿠폰생성(관리자)
  src/main/java/com/threestar/trainus/domain/coupon/admin/controller/AdminCouponController.java
  src/main/java/com/threestar/trainus/domain/coupon/admin/dto/CouponCreateRequestDto.java
  src/main/java/com/threestar/trainus/domain/coupon/admin/dto/CouponCreateResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/admin/mapper/AdminCouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/admin/service/AdminCouponService.java
  src/main/java/com/threestar/trainus/domain/coupon/entity/CouponCategory.java
  src/main/java/com/threestar/trainus/domain/coupon/entity/CouponStatus.java
  src/main/java/com/threestar/trainus/domain/coupon/user/controller/CouponController.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CouponPageResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CreateUserCouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/UserCouponPageResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/UserCouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/entity/Coupon.java
  src/main/java/com/threestar/trainus/domain/coupon/user/entity/CouponCategory.java
  src/main/java/com/threestar/trainus/domain/coupon/user/entity/CouponStatus.java
  src/main/java/com/threestar/trainus/domain/coupon/user/entity/OwnedStatus.java
  src/main/java/com/threestar/trainus/domain/coupon/user/entity/UserCoupon.java
  src/main/java/com/threestar/trainus/domain/coupon/user/mapper/CouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/user/mapper/UserCouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/user/repository/CouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/user/repository/UserCouponRepository.java
  src/main/java/com/threestar/trainus/domain/coupon/user/service/CouponService.java
  src/main/java/com/threestar/trainus/domain/lesson/admin/dto/LessonApplicationResponseDto.java
  src/main/java/com/threestar/trainus/domain/user/entity/User.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
  src/main/java/com/threestar/trainus/global/resolver/LoginUserArgumentResolver.java
  src/test/java/com/threestar/trainus/coupon/CouponServiceTests.java
Labels: feat

#78 Feat: CI 워크플로 구축 테스트
  .github/workflows/gradle.yml
Labels: feat

#82 refactor: float -> double
  src/main/java/com/threestar/trainus/domain/ranking/dto/RankingData.java
  src/main/java/com/threestar/trainus/domain/ranking/dto/RankingResponseDto.java
  src/main/java/com/threestar/trainus/domain/ranking/repository/RankingRepository.java
  src/main/java/com/threestar/trainus/global/config/MockDataInitializer.java
Labels: refactor

#85 feat: PagedResponse 구현 및 레슨 수강 도메인에 적용
  src/main/java/com/threestar/trainus/domain/lesson/student/controller/StudentLessonController.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSearchListWrapperDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/MyLessonApplicationListWrapperDto.java
  src/main/java/com/threestar/trainus/global/unit/PagedResponse.java
Labels: feat

#96 feat: 법정동명 업로드, 검증 테스트 구현
  build.gradle
  src/main/java/com/threestar/trainus/domain/lesson/admin/controller/LocationCsvController.java
  src/main/java/com/threestar/trainus/domain/lesson/admin/entity/Location.java
  src/main/java/com/threestar/trainus/domain/lesson/admin/repository/LocationRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/admin/service/LocationCsvService.java
Labels: feat

#116 test: 동시요청 락 미적용 최대참가자 초과 테스트 작성
  build.gradle
  src/main/java/com/threestar/trainus/domain/lesson/student/service/StudentLessonService.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/controller/LocationCsvController.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/entity/Location.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/repository/LessonParticipantRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/repository/LessonRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/repository/LocationRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/service/AdminLessonService.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/service/LocationCsvService.java
  src/main/java/com/threestar/trainus/global/config/SwaggerConfig.java
  src/test/java/com/threestar/trainus/domain/lesson/student/LessonApplyLockTest.java
Labels: feat

#121 feat: user, profile, metadata 테스트코드
  src/test/java/com/threestar/trainus/domain/metadata/service/ProfileMetadataServiceTest.java
  src/test/java/com/threestar/trainus/domain/profile/entity/ProfileTest.java
  src/test/java/com/threestar/trainus/domain/user/entity/UserTest.java
  src/test/java/com/threestar/trainus/domain/user/service/UserServiceTest.java
Labels: feat

#107 feat: 회원탈퇴 기능 구현
  src/main/java/com/threestar/trainus/domain/comment/repository/CommentRepository.java
  src/main/java/com/threestar/trainus/domain/review/repository/ReviewRepository.java
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/entity/User.java
  src/main/java/com/threestar/trainus/domain/user/repository/UserRepository.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
Labels: feat

#120 feat: 유저쿠폰 테스트코드작성
  .gitignore
  src/main/java/com/threestar/trainus/TrainUsApplication.java
  src/main/java/com/threestar/trainus/global/config/JpaAuditingConfig.java
  src/test/java/com/threestar/trainus/coupon/user/UserCouponControllerTests.java
  src/test/java/com/threestar/trainus/coupon/user/UserCouponServiceConcurrencyTests.java
  src/test/java/com/threestar/trainus/coupon/user/UserCouponServiceTests.java
Labels: feat

#128 refactor: 불변객체 record사용
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CouponPageResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/CreateUserCouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/UserCouponPageResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/dto/UserCouponResponseDto.java
  src/main/java/com/threestar/trainus/domain/coupon/user/mapper/CouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/user/mapper/UserCouponMapper.java
  src/main/java/com/threestar/trainus/domain/coupon/user/service/CouponService.java
  src/main/java/com/threestar/trainus/domain/user/controller/UserController.java
  src/main/java/com/threestar/trainus/domain/user/service/UserService.java
Labels: refactor

#133 feat: 검색 성능개선 및 누락된 검색 조건, 필터링 추가
  src/main/java/com/threestar/trainus/domain/lesson/student/controller/StudentLessonController.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonDetailResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/dto/LessonSearchResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/student/entity/EmptyClass.java
  src/main/java/com/threestar/trainus/domain/lesson/student/entity/LessonSortType.java
  src/main/java/com/threestar/trainus/domain/lesson/student/mapper/LessonSearchMapper.java
  src/main/java/com/threestar/trainus/domain/lesson/student/service/StudentLessonService.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/dto/LessonCreateRequestDto.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/dto/LessonResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/dto/LessonUpdateRequestDto.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/dto/LessonUpdateResponseDto.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/entity/Lesson.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/mapper/LessonMapper.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/repository/LessonRepository.java
  src/main/java/com/threestar/trainus/domain/lesson/teacher/service/AdminLessonService.java
  src/main/java/com/threestar/trainus/global/exception/domain/ErrorCode.java
  src/test/java/com/threestar/trainus/domain/lesson/student/LessonSearchPerformanceTest.java
Labels: feat

#161 feat: base response 형식 적용
  src/main/java/com/threestar/trainus/domain/file/controller/S3Controller.java
  src/main/java/com/threestar/trainus/domain/file/service/S3Service.java
Labels: feat

#147 refactor: 테스트코드 빌더삭제
  src/test/java/com/threestar/trainus/coupon/user/UserCouponControllerTests.java
  src/test/java/com/threestar/trainus/coupon/user/UserCouponServiceTests.java
Labels: refactor
